---
title: "Spatial Models"
description: |
  A short description of the post.
author:
  - name: Adam Peterson
    url: https://apetersonsite.org
date: 08-26-2021
output:
  distill::distill_article:
    self_contained: false
categories:
  - Technical
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(tidyverse)
library(sf)
library(sfnetworks)
library(brms)
```



```{r}

uk <- read_sf("~/Documents/CityData/Philly/geo-data/Neighborhoods_Philadelphia/Neighborhoods_Philadelphia.shp") %>%
  filter(MAPNAME == "Upper Kensington")  %>% 
  st_transform(4326)

shootings <- read_csv("~/Documents/CityData/Philly/Crime/shootings_2015_2020.csv") %>% 
  filter(!is.na(point_x),!is.na(point_y)) %>% 
  filter(point_x > -80,
         year==2015,
         officer_involved=="N") %>% 
  st_as_sf(coords = c("lng","lat")) %>% 
  st_set_crs(4326) %>% 
  st_filter(uk)

streets <- read_sf("~/Documents/CityData/Philly/CompleteStreets-shp/CompleteStreets.shp") %>% 
  st_filter(uk)


sdf <- tibble(street_ix = apply(st_distance(streets,shootings),2,which.min),count=1) %>% 
  group_by(street_ix) %>% count() %>% ungroup()

pltdf <- streets %>% 
  mutate(street_ix = 1:n()) %>% 
  left_join(sdf) %>% 
  mutate(shootings = as.numeric(replace_na(n,0)),
         shooting = factor(as.integer((shootings>=1)*1))) %>% 
  select(shootings,shooting,OBJECTID) %>% 
  filter(OBJECTID!=34432) ## singleton street


ntdf <- as_sfnetwork(pltdf,directed=F)

A <- ntdf %>% 
  tidygraph::convert(tidygraph::to_linegraph) %>% 
  igraph::as_adjacency_matrix()

rownames(A) <- pltdf$OBJECTID
```


```{r}

fit <- brm(shootings ~ 1 + car(A, gr=OBJECTID,type='bym2'),
           data=pltdf,
           data2=list(A=A),
           family = zero_inflated_poisson(),
           cores = 4,iter = 2E3)
```


```{r}
posterior_samples(fit) %>% 
  as_tibble() %>% 
  select(contains("rcar")) %>% 
  mutate(sample_ix = 1:n()) %>% 
  gather(contains("rcar"),key="Par",value="Sample") %>%
  mutate(street_ix = as.integer(str_extract(Par,"[0-9][0-9]?[0-9]?"))) %>% 
  select(street_ix,Sample,sample_ix) %>% 
  group_by(street_ix) %>% 
  summarise(med = median(Sample),Lower = quantile(Sample,0.025),Upper = quantile(Sample,0.975)) %>% 
  inner_join(pltdf %>% mutate(street_ix=1:n())) %>% 
  st_as_sf() %>% 
  ggplot() + geom_sf(aes(color=med)) + 
  theme_void() + scale_color_gradientn(colours = c("black","yellow","red"),limits=c(-2,4))
```