---
title: "Motivation"
description: |
  Urban spaces are more important than ever. Here's three reasons why and a highlight
  of what's to come.
author:
  - name: Adam Peterson 
    url: https://apetersonsite.org
date: 08-07-2021
draft: true
output:
  distill::distill_article:
    self_contained: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```



Of all the things to talk about, why talk about the places where we live? Whether a city, town, suburb, or remote rural residence, the environments we live in define our lives. They constrain – or enable – the things we do, the people we see, the food we eat ... you get the picture. But still – who cares? And why write about them right now?

In this post I'm going to try and convince you that, barring any commitments you
may have made to a myopic nihilism, you care about the built environment, and 
urban spaces^[urban spaces is a term I will use to refer to any space in which humans live
within close proximity to one another] more generally, for at least 3 broad reasons, that will motivate
many of the writings to follow. Here I'll appeal to intuition, cite news articles, 
and be generally "un-academic" or imprecise, but this will likely change
in subsequent posts. For now, I hope to convince you, in broad strokes, 
that these environments are one of humanity's most important inventions and 
they are especially important right now. Here's why. 

# \#1. Social Cohesion: Can we get along?

[Protests](https://www.nytimes.com/interactive/2020/07/03/us/george-floyd-protests-crowd-size.html). [Riots](https://www.wsj.com/articles/riot-at-the-u-s-capitol-11610068066). 
Mobs raging in the street. 
The past two years have shown us more than ever how we struggle to get along at
a societal level.
And that's even before we start talking about the difficulties of getting along
with family at Thanksgiving dinner or the comments on the latest NextDoor post.

Like many things, it is easy to take for granted, but getting along with one 
another is important, not only to reinforce a feeling of safety in where one lives,
but to also provide a sense of belonging and social community.  
If any neighborhood, town or city is going to have real staying power 
it will be because people want to live there.
Safety, belonging and community are each very important ways to satisfy these 
universal human desires.

# \#2. Efficiency: Cheaper, Faster, Farther

How can we do more with less? In an age of increasing income inequality and
tight budgets, you'd think we would spend more time thinking about ways to
stretch the money we have, to do more with less. Efficiency is one of the key
reasons humans began gathering together in primitive towns, all those many 
years ago. Easier to be near the specialized skills – healers, farmers, house
builders, etc. Easier to get to work or play by way of well-established roads.
Cities are fundamentally an economic bargain and you should be better off living
in a city in terms of time and money spent than you would be elsewhere.

# \#3. Climate Change: Life or Death


Floods in [China](https://news.google.com/topics/CAAqKAgKIiJDQkFTRXdvTkwyY3ZNVEZxWkdkd05ITjBNUklDWlc0b0FBUAE?hl=en-US&gl=US&ceid=US%3Aen) and [Germany](https://news.google.com/topics/CAAqKAgKIiJDQkFTRXdvTkwyY3ZNVEZ5Y3pJMmN6RmljeElDWlc0b0FBUAE?oc=3&ceid=US:en), [wildfires](https://news.google.com/topics/CAAqKAgKIiJDQkFTRXdvTkwyY3ZNVEZ5Y3pJMmN6RmljeElDWlc0b0FBUAE?oc=3&ceid=US:en), [drought](https://news.google.com/topics/CAAqKAgKIiJDQkFTRXdvTkwyY3ZNVEZ5Y3pJMmN6RmljeElDWlc0b0FBUAE?oc=3&ceid=US:en) and [heatwaves](https://news.google.com/topics/CAAqKAgKIiJDQkFTRXdvTkwyY3ZNVEZ5Y3pJMmN6RmljeElDWlc0b0FBUAE?oc=3&ceid=US:en) throughout the American mountain west. While I can remember a time when doubt about the perils of climate change was boasted with pride – not too long ago unfortunately – the evidence that the climate is changing and we are the cause only continues to climb with an increasing financial and human cost. 


Of the five biggest [sources of greenhouse gas (GHG) emissions](https://www.breakthroughenergy.org/our-challenge/the-grand-challenges)
at least three can be reduced by improving urban spaces and in so-doing, attract
further residents. 
I'll give a brief example for each.

1. Electricity:
   * A [typical](https://qz.com/40707/meet-the-prototypical-american-home-three-bedrooms-two-bathrooms-and-central-air/) suburban home has, on average, 9 rooms to light, heat and cool everyday. 
   In contrast, an old school [row home](https://www.phila.gov/media/20190521124726/Philadelphia_Rowhouse_Manual.pdf)
   will typically have 4-5 rooms, and a proportionately smaller electric GHG footprint as a result.  
  
2. Transportation:
   * Living closer to other people should mean you don't have to drive as far to work, or that there's easier options through biking and/or public transit instead.

3. Manufacturing:
   * If you're living in a smaller space, you don't want as much stuff. You also don't need to build as many roads, pipes, or other infrastructure because you're getting more use out of the infrastructure you have in place. 
   
# The Reality

It's easy to see in the U.S., whether through [suburban sprawl](https://fivethirtyeight.com/features/how-suburban-are-big-american-cities/), [traffic jammed highways](https://www.forbes.com/sites/niallmccarthy/2020/03/10/traffic-congestion-costs-us-cities-billions-of-dollars-every-year-infographic/?sh=28053bc34ff8), increasing [cost of living](https://www.wsj.com/articles/median-existing-home-price-hit-new-high-in-june-11626963073) or [crime and safety](https://www.cnn.com/2021/04/03/us/us-crime-rate-rise-2020/index.html) issues, our cities fail to live up to the full promise that urban spaces ought to offer. Identifying the nature of these failings explicitly, as well as the solutions that may address them, will form much of the substance of this blog. 