---
title: "Housing Economics - Part II"
description: |
   A Review of "The Economic Implications of Housing Supply"
author:
  - name: Adam Peterson
    url: https://apetersonsite.com/
date: 9-01-2025
draft: true
output: 
  distill::distill_article:
    self_contained: false
    toc: true
    toc_float: true
citation_url: https://xstreetvalidated.com
creative_commons: CC BY
bibliography: housing.bib
categories:
  - Urban Economics
---

```{r libraries, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(haven)
library(tidyverse)
library(patchwork)
library(tidycensus)
theme_set(theme_bw() +
  theme(
    text = element_text(size = 20),
    strip.background = element_blank(),
    legend.title = element_blank()
  ))
here::i_am("_posts/2025-08-09-housing-economics/housing-economics.Rmd")
data_path <- here::here("_posts/2025-08-09-housing-economics/data")
# Wharton Residential Land use index sourced from
# https://real-faculty.wharton.upenn.edu/gyourko/land-use-survey/
```

```{r}
#| label: wharton-reg-index
land_reg <- read_dta(file.path(
  data_path,
  "WHARTON LAND REGULATION DATA_1_24_2008.dta"
)) |>
  mutate(year = 2008) |>
  select(year, msaname99, state, weight, WRLURI)
```

```{r}
#| label: american-housing-survey
#| eval: FALSE
ahs <- read_sas(file.path(data_path, "ahs2007n.sas7bdat")) |>
  select(CPRICE, LPRICE, contains("REPWGT"), REGION, METRO3, CMSA, SMSA) |>
  rename(
    CurrentPrice = "CPRICE",
    LandPrice = "LPRICE",
    CensusRegion = "REGION",
    Metro = "METRO3"
  )
```